# Generated by Django 5.1.1 on 2024-09-26 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesModel',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(100)])),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(45)])),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(45)])),
                ('last_name', models.CharField(max_length=45, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(45)])),
                ('email', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(60)])),
                ('password', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(200)])),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacationsModel',
            fields=[
                ('vacation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(250)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('image_name', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(300)])),
            ],
            options={
                'db_table': 'vacations',
                'managed': False,
            },
        ),
    ]
