# Generated by Django 5.1.1 on 2024-09-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likesmodel',
            options={},
        ),
    ]
