# Generated by Django 5.1.1 on 2024-09-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_likesmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likesmodel',
            options={'managed': False},
        ),
    ]
